# Generated by Django 3.0.5 on 2020-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('addr', models.CharField(default='Beijing', max_length=50, verbose_name='address')),
                ('city', models.CharField(default='Beijing', max_length=20, verbose_name='city')),
                ('mail', models.CharField(default='xxx', max_length=50, verbose_name='mail')),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
